### ISSUE TITLE
如果可以的话，可以把lobby依赖整合到里面来嘛

### ISSUE THREAD

**Issue by Astra-520** [JHXSMatthew/UHC_lobby#1]
rt，qwq

**Comment by JHXSMatthew** [comment]
看起来依赖
    <orderEntry type="library" name="lobby_Statistics" level="project" />
    <orderEntry type="library" name="Lobby_Display" level="project" />
    <orderEntry type="library" name="lobby_Gui" level="project" />
    <orderEntry type="library" name="Lobby_ServerSelctor" level="project" />
    <orderEntry type="library" name="SQL_Lib" level="project" />

可以分别编译对应的库，生成jar后编译这个

**Comment by JHXSMatthew** [comment]
非常抱歉目前不会再继续支持这个项目，如果感兴趣可以自行探索。
